# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MeetingMood < Formula
  desc "Web app to collect people's moods in a meeting"
  homepage "https://github.com/geeksforsocialchange/meeting-mood"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geeksforsocialchange/meeting-mood/releases/download/v0.3.2/meeting-mood_Darwin_x86_64.tar.gz"
      sha256 "38c7e9a994224926b8eb3248165df6de50c3caa9814fc780b2c1aa8bf8dbc6f6"

      def install
        bin.install "meeting-mood"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geeksforsocialchange/meeting-mood/releases/download/v0.3.2/meeting-mood_Darwin_arm64.tar.gz"
      sha256 "f1649ca0dbcc6d4d01fba5f8343142003207b72a6ef43e193f867b405791b941"

      def install
        bin.install "meeting-mood"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/geeksforsocialchange/meeting-mood/releases/download/v0.3.2/meeting-mood_Linux_x86_64.tar.gz"
      sha256 "bd561ec158cfff86a3bb47cd53d05b2f978d67f8a2b4127e1686faf65ac1cee1"

      def install
        bin.install "meeting-mood"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geeksforsocialchange/meeting-mood/releases/download/v0.3.2/meeting-mood_Linux_arm64.tar.gz"
      sha256 "98d11306940e6e09ae6b5c78a9bc24a0e629437d9fbe40b40f0e4608c0bd002b"

      def install
        bin.install "meeting-mood"
      end
    end
  end
end
