# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MeetingMood < Formula
  desc "Web app to collect people's moods in a meeting"
  homepage "https://github.com/wheresalice/meeting-mood"
  version "0.2.1"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/WheresAlice/meeting-mood/releases/download/v0.2.1/meeting-mood_Darwin_x86_64.tar.gz"
    sha256 "e4d3d4f4c2b8bcd9171202fd42138e1357cfc05afdd0441e7fd8f3478ffa0a7e"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/WheresAlice/meeting-mood/releases/download/v0.2.1/meeting-mood_Darwin_arm64.tar.gz"
    sha256 "8353503a5fc3d1434db6c9c66773a8feba7821bfd7efcb960d7bb0cb893be77b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/WheresAlice/meeting-mood/releases/download/v0.2.1/meeting-mood_Linux_x86_64.tar.gz"
    sha256 "9b474372e24680d719e2a99ee15e060c9e20b1fe9c189783752b30bb01f85dad"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/WheresAlice/meeting-mood/releases/download/v0.2.1/meeting-mood_Linux_arm64.tar.gz"
    sha256 "ee38f2f13c89358f9cc0c9772f45476e7e391f1fa01f074d65423de17b01e3a3"
  end

  def install
    bin.install "meeting-mood"
  end
end
